properties(
  [
    parameters(
      [
        string(
          defaultValue: 'SSHPRIVKEY',
          description: 'SSH private key Jenkins credential ID for Beaker/SSH operations.',
          name: 'SSHPRIVKEYCREDENTIALID'
        ),
        string(
          defaultValue: 'SSHPUBKEY',
          description: 'SSH public key Jenkins credential ID for Beaker/SSH operations.',
          name: 'SSHPUBKEYCREDENTIALID'
        ),
        string(
          defaultValue: 'KEYTAB',
          description: 'Kerberos keytab file Jenkins credential ID for Beaker/SSH operations.',
          name: 'KEYTABID'
        ),
        string(
          defaultValue: 'root',
          description: 'Username for ssh connection.',
          name: 'SSH_USERNAME'
        ),
        string(
          defaultValue: 'kernelci-04.khw.lab.eng.bos.redhat.com',
          description: 'Hostname for ssh connection.',
          name: 'SSH_HOSTNAME'
        )
      ]
    )
  ]
)

node("provisioner-v0.3") {
  // Install ssh keys
  withCredentials([file(credentialsId: params.SSHPRIVKEYCREDENTIALID, variable: 'SSHPRIVKEY'),
                  file(credentialsId: params.SSHPUBKEYCREDENTIALID, variable: 'SSHPUBKEY')]) {
    env.HOME = "/home/jenkins"
    sh """
      whoami
      mkdir -p ~/.ssh
      cp ${SSHPRIVKEY} ~/.ssh/id_rsa
      cp ${SSHPUBKEY} ~/.ssh/id_rsa.pub
      chmod 600 ~/.ssh/id_rsa
      chmod 644 ~/.ssh/id_rsa.pub
      cat ~/.ssh/id_rsa.pub
    """
  }

  // Test starts here
  sh """
    ping -c 2 ${SSH_HOSTNAME}
    echo ${params.SSH_USERNAME}@${params.SSH_HOSTNAME}
    ssh -T -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${params.SSH_USERNAME}@${params.SSH_HOSTNAME};
    echo 'Hello World'
    hostname
    pwd
    whoami
    cd /home/openshift/openshift-ansible
    git pull
    cd ..
    ansible all -m ping --private-key=vminstall.key
    ansible all -m 'shell systemctl start docker' --private-key=vminstall.key    
  """
}
